### ISSUE TITLE
Problems when encoding a numerical column using categorical featurizers

### ISSUE THREAD

**Issue by rcap107** [awslabs/datawig#140] opened 2020-09-30 14:29 UTC
Hello, 
I am working on a synthetic categorical dataset that contains information about people and their location, with a format similar to

```
name, city, zip
john, paris, 1234
frank, rome, 718
```

In this situation the zip codes are integers, but I want to treat them as categorical data because I do not want to infer information based on their numerical properties. 

In my code, I implemented the imputer both as
```
data_encoder_cols = [datawig.BowEncoder('zip')]
label_encoder_cols = [datawig.CategoricalEncoder('city')]
data_featurizer_cols = [datawig.BowFeaturizer('zip', max_tokens=df_train['zip'].nunique())]
```
and as 
```
data_encoder_cols = [datawig.CategoricalEncoder('zip')]
label_encoder_cols = [datawig.CategoricalEncoder('city')]
data_featurizer_cols = [datawig.EmbeddingFeaturizer('zip', max_tokens=df_train['zip'].nunique())]
```

In the first case, `imputer.fit(df_train)` failed because (I'm assuming) the `zip` column was automatically cast back to integer (even though I had previously set it to `object`). The exception I'm getting is `AttributeError: 'float' object has no attribute 'lower'
`
In the second case, the training failed in a weird way I can't explain, with the exception `IndexError: index 716 is out of bounds for axis 0 with size 715
`

I tried `df_dirty['zip'] = df_dirty['zip'].apply(lambda x: 'i' + str(x))` as a workaround, so that the zip codes are forced to be seen as strings. In this case, the code with CategoricalEncoder still failed with a similar error (719 instead of 716), while the BoWEncoder runs (slowly). 

What's the correct way of treating numerical columns as categorical ones?

**Comment by felixbiessmann** [comment] 2020-09-30 20:07
Hi,

thanks for the feedback!

I'd recommend to use the SimpleImputer, that often works well enough, especially when you combine it with the fit_hpo (which does some model selection, might take a while). 

In your case, it seems that you wouldn't have that problem, here are some examples of how to cast numbers in your zip column into strings and thereby tell SimpleImputer to treat them as categorical variables:

```
import datawig, random, numpy

# helper function to create synthetic data
def get_df():
  # generate some random strings with dependencies between col 1 and 2
  df = datawig.utils.generate_df_string()
  df.columns = ['city','zip']

  # replace the to-be-imputed zip strings with their histogram index
  zip_hist = df['zip'].value_counts()
  df['zip'] = df['zip'].replace(zip_hist.index,range(len(zip_hist)))

  # mask 10% of the values
  df = df.mask(numpy.random.rand(*df.shape) > .9)
  return df
```

Here's how to use SimpleImputer with a numeric loss function on the zip code:

```
df = get_df()
# create a SimpleImputer and impute the missing **numeric** target variable
imputer = datawig.SimpleImputer(input_columns=['city'],output_column='zip')
imputer.fit(df)
imputer.predict(df)
```

city | zip | zip_imputed
-- | -- | --
NaN | 1.0 | 0.550981
MxVEf A9LPJ yBzUU CBzLZ mXbpg Qcbqh | 0.0 | -0.000127
wWcGG Y6uJP A9LPJ AXTAc g0Sud iSmwT | 0.0 | 0.000031
g0Sud XTkgC U8zpS 3iULe dy0Ry ke4Fo | 1.0 | 1.000271
NaN | 1.0 | 0.550981

Here's how I casted the numbers to strings in the input data frame. SimpleImputer now uses a categorical loss:
```
df = get_df()

# if you do want to model the numbers as strings, you can cast them (as you probably did?)
df['zip'] = df['zip'].astype(str)

# create a SimpleImputer and impute the missing **numeric** target variable
imputer = datawig.SimpleImputer(input_columns=['city'],output_column='zip')
imputer.fit(df)
imputer.predict(df)
```

city | zip | zip_imputed | zip_imputed_proba
-- | -- | -- | --
mAjVX OE3cV 9M8NN 2bqtl S9KWV nIdLS | 0.0 | 0.0 | 0.932502
lN73y MoCsr srguM S9KWV yAwxf yFof3 | 0.0 | 0.0 | 0.998486
Cv29z yZ2rz Wbdfc riVrx IAYHH MCjDX | 1.0 | 1.0 | 0.997059
Ic8Eb 78BCo ZEuwq z1Glb riVrx 4Awdx | 1.0 | 1.0 | 0.995454
w6cal zpsni iziDV S9KWV OE3cV w6cal | nan | nan | 0.964353

And if you want to mark the nans as those that need to be imputed, you might want to exclude them:

```
df = get_df()
df.loc[df['zip'].isnull()==False, 'zip'] = df['zip'].astype(str)

# create a SimpleImputer and impute the missing **numeric** target variable
imputer = datawig.SimpleImputer(input_columns=['city'],output_column='zip')
imputer.fit(df)
imputer.predict(df)
```

city | zip | zip_imputed | zip_imputed_proba
-- | -- | -- | --
hg9bG RRyrd enhXS cxfRG vV0T1 XnnvT | 0.0 | 0.0 | 0.999991
ueVJW vV0T1 hVGb6 ti25A Ng8oa YEZoP | 0.0 | 0.0 | 1.000000
U77B6 hg9bG kJTgQ 1FCX2 brBin B8ks4 | 1.0 | 1.0 | 1.000000
NaN | 1.0 | 0.0 | 0.780107
B8ks4 e9nyr hg9bG yJQJW Zqkit 0TyVz | 1.0 | 1.0 | 1.000000

And even simpler, you could use the convenience function ``datawig.SimpleImputer.complete``.

Hope that helps?

**Comment by felixbiessmann** [comment] 2020-10-04 13:04
Closing this issue for now, feel free to reopen, if the problem is not solved.

**Closed by felixbiessmann** 2020-10-04 13:04 UTC

**Comment by rcap107** [comment] 2020-10-09 13:04
Hello, I have been working on a different variant of the dataset which has the form
```

fname | lname | gender | areacode | phone | city | state | zip | maritalstatus | haschild | salary | rate | singleexemp | marriedexemp | childexemp
Xiang | Lockington | M | 603 | 943-8778 | STRATHAM | NH | i3885 | M | N | 85000 | 0.000000 | 0 | 0 | 0
Mikael | Schriber | M | 808 | 295-2381 | HALEIWA | HI | i96712 | M | N | 85000 | 8.250000 | 0 | 2080 | 0
Junjie | Geurts | F | 302 | 530-6011 | NEWARK | DE | i19725 | M | N | 50000 | 5.268182 | 0 | 220 | 0
Hichem | Cieplinski | M | 808 | 676-4868 | HONOLULU | HI | i96807 | S | Y | 15000 | 3.743421 | 1040 | 0 | 1040
```

As was suggested, I've tried to use `SimpleImputer.complete(df)` to impute the missing values in the dataset.  I noticed that if I introduced missing values in the `city` or `zip` column (after changing `zip` so that it's seen as a categorical column), then they wouldn't be imputed. I'm guessing that happens because the number of unique values in those columns is higher than what is allowed by the heuristic. I didn't find a parameter to tweak that, is it possible to change it? 

I also tried `SimpleImputer()` with different combinations of columns, but I did not obtain good results. 

Going back to my original post, the `Imputer()` class seemed like the best fit for my use case, however I had to stop the execution after using the categorical imputer in the `zip` case as it was taking to long. Is that the reason why the heuristic is in place? 

Another thing that I noticed was that the imputer was imputing data for non-missing values. Is it possible to prevent this from happening? 

Thanks!

**Comment by felixbiessmann** [comment] 2020-10-10 12:32
As for your first question, I would recommend to double check in the metrics files whether the imputation precision for your imputed categories are high enough. Just because the code runs through doesn't mean that you should trust the predictions. I guess I'd use the `SimpleImputer`'s fit and predict methods with a precision threshold, that way you will only get imputations if an imputation is above a certain precision level. 

As for your question on how to use the  `Imputer`, I'm not sure I understand what the input or output is. If the zip code should not be treated as number, I'd recommend the [`BowEncoder`](https://datawig.readthedocs.io/en/latest/source/API.html?highlight=bowencoder#datawig.column_encoders.BowEncoder) with characters as tokens (that's the default), with a featurizer. Depending on your RAM and data set size, this could really take a long time, to double check what's going on and whether it would work, I usually work on a subsample of my data sets. 

As for the question what gets imputed and what not: 
- if you use `SimpleImputer.complete`, only null values will be imputed
- if you use `SimpleImputer.predict` you will get a new column and you can decide for yourself, which values you'd like to use.
